# Generated by Django 5.1.3 on 2025-07-30 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
