# Generated by Django 5.2.3 on 2025-06-23 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic Life Support (BLS)'), ('advanced', 'Advanced Life Support (ALS)'), ('critical', 'Critical Care Transport (CCT)'), ('emergency', 'Emergency Response Vehicle')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('base_location', models.CharField(max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipment_list', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ambulance', to='accounts.driverprofile')),
            ],
            options={
                'verbose_name': 'Ambulance',
                'verbose_name_plural': 'Ambulances',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulances.ambulance')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile')),
            ],
            options={
                'verbose_name': 'Ambulance Assignment',
                'verbose_name_plural': 'Ambulance Assignments',
                'unique_together': {('driver', 'ambulance', 'assigned_date')},
            },
        ),
    ]
