# Generated by Django 5.1.3 on 2025-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
